### ISSUE TITLE
Operating Reserves Constraint Error

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#163]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Constraints set by the configuration `operating_reserve:` not functioning. Error comes from https://github.com/PyPSA/pypsa-eur/blob/0d2aac5dd26ff03d06be2aabe19daef1e4317d2e/scripts/solve_network.py#L435-L437

Where `p_nom_vres` of shape (Generators,) doesn't broadcast over the `(-EPSILON_VRES * capacity_factor)` of shape (Generators, snapshots). 

This is an error thrown in pypsa-eur code. I need to run pypsa-eur to see if their network also has this issue, in which case this would be a PR to pypsa-eur.

### Steps To Reproduce

Running Solve_Network with : 
```
  operational_reserve:
    activate: True
    epsilon_load: 0.02
    epsilon_vres: 0.02
    contingency: 4000
```
