### ISSUE TITLE
Question about CO2 mu value under multiple planning horizon

### ISSUE THREAD

**Issue by casinocullen** [PyPSA/pypsa-usa#389]
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

I have a question about mu value under CO2 global constraint. When I selected multiple planning horizons, ie., 2030 + 2040, the mu of CO2 becomes -563.734746	while if I only model 2030, the mu of CO2 is nearly 0. I am confused about this variable here and couldn't find too many codes explaining that. But while the mu of CO2 is large, the model is trying to retire all CO2 emitting plants, and build way too much renewables...

Any thoughts on this?

**Comment by ktehranchi** [comment]
Hey Chen- the mu values is the shadow price of the carbon constraint. The larger magnitude signifies that the cost of alleviating that constraint by 1 unit of your co2 constraint would cost 563$. IE higher shadow prices make sense to a higher renewable resource build.

Maybe you can share more about your model configuration or more details on the issue with the build

**Comment by casinocullen** [comment]
@ktehranchi yeah that's what I figured that it means the shadow price of CO2. I guess my question is, why I only changed the planning horizon from 2030 only to 2030 + 2040, the shadow price increased that much (from ~0 to $563). Besides that, I didn't change anything else in the config.

This is the part of config file and the only place I changed is `planning_horizons` from `-2030` to `-2030 -2040`: 

```
scenario:
  interconnect: [texas] #"usa|texas|western|eastern"
  clusters: [12]
  opts: [Co2L0.2]
  ll: [v1.0]
  scope: "total" # "urban", "rural", or "total"
  sector: "E" # G
  planning_horizons:
   -  2030
   -  2040   #(2018-2023, 2030, 2040, 2050)
```
Thanks so much for looking into this!
