### ISSUE TITLE
Clustering by 'state' throws error

### ISSUE THREAD

**Issue by ktehranchi** [PyPSA/pypsa-usa#45]
When clustering based on the state, an error is thrown related to clustering with 'Utah'. Root cause not identified yet.

```
  cluster_network:
    algorithm: kmeans
    feature: solar+onwind-time
    aggregation_zones: 'balancing_area' # balancing_area, country, or state. # Currently issue in State aggregation- error thrown on Utah
```
