### ISSUE TITLE
Demand response costs 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#508]
### Feature Request

Allow different marginal costs to shift different energy carriers for sector studies. Something along the lines of: 

```
demand_response:
  shift: 10 # as a percent 
  marginal_cost: 5 # optional global value
```

or 

```
demand_response:
  shift: 10 # as a percent 
  marginal_cost:
    elec: 5 # cost per carrier
    space_heat: 2
    cooling: 3
```
