### ISSUE TITLE
Toggle carriers allowed to participate in DR

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#511]
### Feature Request

For sector studies, DR can be turned on/off at a sector level. For example, residenitial can participate, while industrical can not. For my study I need to add this at a carrier level as well. ie. Allowing residential heating to participate, but not residential electrical. 

### Suggested Solution

probably reformulate the demand response config like so: 

```yaml
service_sector:
  demand_response: 
    electricity: 
      shift: inf
      marginal_cost: 10
    heat: 
      shift: inf
      marginal_cost: 10
```
