### ISSUE TITLE
Configuration options for spatital/temporal cost multipliers 

### ISSUE THREAD

**Issue by trevorb1** [PyPSA/pypsa-usa#59]
### Feature Request

It would be good to have configuration file options for how to apply cost data 

### Suggested Solution

A simple implementation of the options we could add is given below. This could be good for doing uncertainty analysis in the future 

```yaml
costs:
  multipliers:
     regional:
       capex: true # apply capex multipliers at a state level
       fuel: true # apply fuel costs at a state level
     temporal:
       fuel: true # apply monthly variance in fuel costs
```
